server:
  port: 8082
spring:
  application:
    name: account-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/account_db
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL55Dialect
#  cloud:
#    config:
eureka:
  client:
  serviceUrl:
    defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true
domain:
  jwt:
    secret: mysecret
